[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "composites-property-prediction"
version = "0.1.0"
description = "Учебный проект прогнозирования свойств композиционных материалов"
requires-python = ">=3.12,<3.13"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra -p no:cacheprovider"
